// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aapuyxngpflmouahmsqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhcHV5eG5ncGZsbW91YWhtc3FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2ODEwNTQsImV4cCI6MjA1NjI1NzA1NH0.8_xR7LGa6ZDX9KTuV9_54NqGB16-4T-wyKn2FIBTH_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);